app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")
Sys.sleep(20)
app$snapshot()
app$setInputs(table_phe_rows_selected = 1000, allowInputNoBinding_ = TRUE, timeout_ = 15000)
app$snapshot()
app$setInputs(instruct = "click")
Sys.sleep(2)
app$snapshot()
